
trigger: none

pool: New-Ferji-pool

jobs:
 - job: terraforminit
   steps: 
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/todoapp_infra'
        backendServiceArm: 'ferji-connectiom'
        backendAzureRmStorageAccountName: 'ferjistorageacoount'
        backendAzureRmContainerName: 'farji-container'
        backendAzureRmKey: 'terraform.tfstate'

 - job: terraformplan
   steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/todoapp_infra'
        environmentServiceNameAzureRM: 'ferji-connectiom'

 - job: terraformapply
   steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)todoapp_infra'
        environmentServiceNameAzureRM: 'ferji-connectiom'