name: 'First Terraform Infra'

on: workflow_dispatch

jobs:
  
  terraform-jobs:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

  

          
    
    
  
